blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/florian-berger/football-discord-rp/discussions
    about: You have a question that is not a bug or feature/league request? Please ask here to keep the issues clean.