name: Build setup and release

on:
  push:
    tags:
      - 'v*.*'
      - 'v*.*.*'

jobs:
  build-setup:
    # Windows runner needs to be used for WiX builds
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v4

    - name: 'Setup .NET10 SDK'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0'

    - name: 'Determine version from tag'
      id: prepare_build
      run: |
        # Remove the leading 'v' from the tag name to get the version
        $version = "${{ github.ref_name }}".Substring(1)
        Add-Content -Path $Env:GITHUB_OUTPUT -Value "buildVersion=$version"

    - name: 'Build projects'
      run: |
        $version = ${{ steps.prepare_build.outputs.buildVersion }}
        & .\UpdateProjectVersion.ps1 -NewVersion $version
        dotnet build football-discord-rp.Setup/football-discord-rp.Setup.wixproj -c Release /p:Version=$version /p:AssemblyVersion=$version /p:FileVersion=$version /p:InformationalVersion=$version
      shell: powershell

    - name: 'Rename setups'
      run: |
        $version = ${{ steps.prepare_build.outputs.buildVersion }}

        $basePath = "football-discord-rp.Setup/bin/Release/"

        # Rename the setup
        $enFile = Get-ChildItem -Path "$basePath/en-US/" -Filter "*.msi" | Select-Object -First 1
        if ($enFile) {
            $newName = "Football_Discord-RP-$version-en.msi"
            $newPath = Join-Path $enFile.DirectoryName $newName
            Write-Host "Renaming $($enFile.Name) to $newName"
            Rename-Item -Path $enFile.FullName -NewName $newName
        }
      shell: powershell

    - name: 'Create GitHub release as draft'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Version ${{ github.ref_name }}
        files: |
          football-discord-rp.Setup/bin/Release/**/*.msi
        draft: true
        body: |
          ## What's changed
          - Fill the content here

          **Full Changelog**: Insert link here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}